spring.application.name=DienCamTamThe

spring.datasource.url=jdbc:mysql://dien-cam-tam-the-nguyentrinhvo01012005-d6b5.j.aivencloud.com:17507/dien_cam_tam_the?sslMode=REQUIRED
spring.datasource.username=avnadmin
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect